apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-service
  namespace: ns-bookmark-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmark-service
  template:
    metadata:
      labels:
        app: bookmark-service
    spec:
      containers:
        - name: bookmark-service
          image: {{ .Values.bookmarkService.image }}:{{ .Values.bookmarkService.tag }}
          ports:
            - containerPort: {{ .Values.bookmarkService.port }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.bookmarkService.env.POSTGRES_HOST }}
            - name: POSTGRES_PORT
              value: "{{ .Values.bookmarkService.env.POSTGRES_PORT }}"
            - name: POSTGRES_DB
              value: {{ .Values.bookmarkService.env.POSTGRES_DB }}
            - name: POSTGRES_USER
              value: {{ .Values.bookmarkService.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password