apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-service
  namespace: ns-bookmark-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmark-service
  template:
    metadata:
      labels:
        app: bookmark-service
    spec:
      containers:
        - name: bookmark-service
          image: {{ .Values.bookmarkService.image }}:{{ .Values.bookmarkService.tag }}
          ports:
            - containerPort: {{ .Values.bookmarkService.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.POSTGRES_HOST }}:{{ .Values.POSTGRES_PORT }}/{{ .Values.POSTGRES_DB}}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.bookmarkService.env.POSTGRES_USER }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password