apiVersion: v1
kind: Service
metadata:
  name: bookmark-service
  namespace: ns-bookmark-service
spec:
  selector:
    app: bookmark-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: {{ .Values.bookmarkService.port }}
  type: LoadBalancer
