apiVersion: v1
kind: Service
metadata:
  name: bookmark-service
spec:
  selector:
    app: bookmark-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.bookmarkService.port }}